### ISSUE TITLE
Bedevere no longer comments on PRs that break stable buildbots

### ISSUE THREAD

**Issue by tiran** [python/buildmaster-config#333] opened 2022-07-09 11:46 UTC
Bedevere used to comment on PRs that break stable buildbots, e.g. https://github.com/python/cpython/pull/17975#issuecomment-830911179 .

It seems like the feature no longer works. For example PR https://github.com/python/cpython/pull/94549 broke four stable [WebAssembly buildbots](https://buildbot.python.org/all/#/builders?tags=%2Bwasm) but bedever-bot did not add a warning to the PR.

**Comment by pablogsal** [comment] 2022-07-09 14:42
I will fix it when I am back home, but I think the problem is that the regular expression to identify the issue was updated to check for GH- but the commit that was merged had "gh-". We need to add `ignorecase` after checking that this is indeed the problem.

**Closed** 2022-07-09 16:33 UTC
